# 1.  Import Libraries & Load Helper Functions

In [1]:
import os, sys
import pandas as pd

project_root = os.path.abspath("..")
sys.path.insert(0, project_root)

# Load the Raw Dataset

In [2]:

csv_path = os.path.join(project_root, "data", "raw", "netflix_data.csv")

print(csv_path)  # just to confirm

df_raw = pd.read_csv(csv_path)

df_raw.head()

df_original = df_raw.copy()

from scripts.cleaning_utils import clean_dataframe

c:\Users\olayi\OneDrive\Desktop\Data\python-projects\projects\netflix-analysis-project\data\raw\netflix_data.csv

# Initial Exploration

In [3]:
df_raw.shape
df_raw.info()
df_raw.isna().sum()
df_raw.sample(5)

<class 'pandas.DataFrame'>
RangeIndex: 4812 entries, 0 to 4811
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       4812 non-null   str
 1   type          4812 non-null   str
 2   title         4812 non-null   str
 3   director      4812 non-null   str
 4   cast          4812 non-null   str
 5   country       4812 non-null   str
 6   date_added    4812 non-null   str
 7   release_year  4812 non-null   int64
 8   duration      4812 non-null   int64
 9   description   4812 non-null   str
 10  genre         4812 non-null   str
dtypes: int64(2), str(9)
memory usage: 413.7 KB

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre
4660,s7518,Movie,Wedding Unplanned,Reem Kherici,"Reem Kherici, Nicolas Duvauchelle, Julia Piato...",France,"October 19, 2017",2017,94,Mathias's girlfriend finds a business card for...,Comedies
1909,s3055,Movie,Iron Cowboy: The Story of the 50.50.50,Jacob Schwab,James Lawrence,United States,"July 19, 2019",2018,77,A record-setting triathlete dares to complete ...,Documentaries
1051,s1661,Movie,Dean,Demetri Martin,"Demetri Martin, Kevin Kline, Gillian Jacobs, R...",United States,"March 15, 2020",2016,94,"As his father takes steps to move on, a New Yo...",Comedies
232,s324,Movie,After,Jenny Gage,"Josephine Langford, Hero Fiennes Tiffin, Selma...",United States,"October 9, 2019",2019,106,Wholesome college freshman Tessa Young thinks ...,Dramas
4353,s7003,Movie,The Wishing Tree,Manika Sharma,"Shabana Azmi, Makrand Deshpande, Harshpreet Ka...",India,"June 5, 2017",2017,117,Five children living on the edge of a forest b...,Children

### Notes from initial inspection

- `date_added` is stored as a string and needs conversion.
- `duration` mixes minutes and seasons.
- Some titles contain strange unicode characters.
- Missing values appear in director, cast, and country.
- Column names need standardization.

# Apply Cleaning Pipeline

In [4]:
cleaned_df = clean_dataframe(df_raw)
cleaned_df.head()

2026-05-18 13:25:00,133 - INFO - Starting dataframe cleaning...
2026-05-18 13:25:00,135 - INFO - Cleaning text column: title
2026-05-18 13:25:00,140 - INFO - Cleaning text column: director
2026-05-18 13:25:00,146 - INFO - Cleaning text column: cast
2026-05-18 13:25:00,152 - INFO - Cleaning text column: country
2026-05-18 13:25:00,156 - INFO - Cleaning text column: description
2026-05-18 13:25:00,162 - INFO - Cleaning text column: genre
2026-05-18 13:25:00,165 - INFO - Parsing date_added column
2026-05-18 13:25:00,176 - INFO - Splitting duration into type
2026-05-18 13:25:00,178 - INFO - Filling missing values for director and country
2026-05-18 13:25:00,179 - INFO - Creating decade column
2026-05-18 13:25:00,180 - INFO - Dataframe cleaning complete.

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre,year_added,duration_type,decade
0,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,2016-12-23,2016,93,After a devastating earthquake hits Mexico Cit...,Dramas,2016.0,min,2010
1,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,2018-12-20,2011,78,"When an army recruit is found dead, his fellow...",Horror Movies,2018.0,min,2010
2,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,2017-11-16,2009,80,"In a postapocalyptic world, rag-doll robots hi...",Action,2017.0,min,2000
3,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,2020-01-01,2008,123,A brilliant group of students become card-coun...,Dramas,2020.0,min,2000
4,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,2017-07-01,2016,1,A genetics professor experiments with a treatm...,International TV,2017.0,Seasons,2010

# Inspect Cleaned Data

In [5]:
cleaned_df.info()
cleaned_df.isna().sum()
cleaned_df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 4812 entries, 0 to 4811
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   show_id        4812 non-null   str
 1   type           4812 non-null   str
 2   title          4812 non-null   str
 3   director       4812 non-null   str
 4   cast           4812 non-null   str
 5   country        4812 non-null   str
 6   date_added     4808 non-null   datetime64[us]
 7   release_year   4812 non-null   int64
 8   duration       4812 non-null   int64
 9   description    4812 non-null   str
 10  genre          4812 non-null   str
 11  year_added     4808 non-null   float64
 12  duration_type  4812 non-null   str
 13  decade         4812 non-null   int64
dtypes: datetime64[us](1), float64(1), int64(3), str(9)
memory usage: 526.4 KB

,show_id,type,title,director,cast,country,date_added,release_year,duration,description,genre,year_added,duration_type,decade
count,4812,4812,4812,4812,4812,4812,4808,4812.000000,4812.000000,4812,4812,4808.000000,4812,4812.000000
unique,4812,2,4811,3615,4690,72,NaN,NaN,NaN,4807,31,NaN,2,NaN
top,s2,Movie,Consequences,"Raúl Campos, Jan Suter",Samuel West,United States,NaN,NaN,NaN,When pretty new neighbor Seema falls for their...,Dramas,NaN,min,NaN
freq,1,4677,2,18,10,1886,NaN,NaN,NaN,2,1343,NaN,4677,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-08 01:15:46.422629,2012.711554,99.566708,NaN,NaN,2018.514143,NaN,2007.290108
min,NaN,NaN,NaN,NaN,NaN,NaN,2008-01-01 00:00:00,1942.000000,1.000000,NaN,NaN,2008.000000,NaN,1940.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,2018-03-01 00:00:00,2011.000000,88.000000,NaN,NaN,2018.000000,NaN,2010.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,2019-03-02 00:00:00,2016.000000,99.000000,NaN,NaN,2019.000000,NaN,2010.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-07 00:00:00,2018.000000,116.000000,NaN,NaN,2020.000000,NaN,2010.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,2021-01-16 00:00:00,2021.000000,253.000000,NaN,NaN,2021.000000,NaN,2020.000000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.517978,30.889305,NaN,NaN,1.382755,NaN,9.470090

# Quick Checks

In [6]:
'Check duration parsing'

cleaned_df[["duration",  "duration_type"]].head(10)


'Check date parsing'

cleaned_df[["date_added", "year_added"]].sample(10)


'Check decade feature'

cleaned_df["decade"].value_counts().sort_index()

print(cleaned_df[['duration', 'duration_type']].head(10))

   duration duration_type
0        93           min
1        78           min
2        80           min
3       123           min
4         1       Seasons
5        95           min
6       119           min
7       118           min
8       143           min
9       103           min

# Save Cleaned Dataset

In [7]:
output_path = os.path.join(project_root, "data", "processed", "netflix_cleaned.csv")
cleaned_df.to_csv(output_path, index=False)

output_path

'c:\\Users\\olayi\\OneDrive\\Desktop\\Data\\python-projects\\projects\\netflix-analysis-project\\data\\processed\\netflix_cleaned.csv'

The cleaned dataset has been saved to:

`data/processed/netflix_cleaned.csv`

This file will be used in:
- Notebook 2 (1990s Deep Dive)
- Notebook 3 (Global Trends & Evolution)

### Summary of Cleaning Steps

- Standardized text fields and removed invisible unicode characters  
- Converted `date_added` to datetime  
- Split `duration` into `duration_int` and `duration_type`  
- Filled missing values in director, cast, and country  
- Added `year_added` and `decade` columns  
- Exported a clean dataset for further analysis  

The dataset is now ready for deeper exploration in the next notebooks.